version: "2"
services:
  db:
    image: mysql:5.7
    command: mysqld --max-connections=1000 --sql-mode="ANSI,ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_ENGINE_SUBSTITUTION,NO_KEY_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,TRADITIONAL"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $SQL_CLIENT_PASSWORD
      MYSQL_DATABASE: $SQL_INTERNAL_DATABASE
    ports:
      - "127.0.0.1:3306:3306"

  kinesis:
    image: dlsniper/kinesalite
    command: kinesalite --port 7661
    ports:
      - "127.0.0.1:7661:7661"

  rabbit:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbit-host
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
